#!/bin/bash
set -e

# Make link
chmod +x /opt/chsrt/chsrt
ln -s /opt/chsrt/chsrt /usr/bin/chsrt 2>/dev/null || true

# Update MAN pages
#mandb -q 2>/dev/null || true

# Just loading to suppress warning
. /usr/share/debconf/confmodule || true

# Done
exit 0
